### ISSUE TITLE
The download script is not working

### ISSUE THREAD

**Issue by davidcastells** [GiantSteps/giantsteps-key-dataset#2]
It looks like the audio files are no longer in beatport, or the URLs changed.

Could you check it out?

**Comment by anxefaraldo** [comment]
In principle, the script (/.audio.dl.sh) should download the missing files from a backup location. I just tried and for me it does download the files (from the alternate location).

You might want to check the revised Giantsteps dataset, with some corrections and improvements over the original publication:

https://zenodo.org/record/1095691#.Wqb_b5P48dk

**Comment by davidcastells** [comment]
Yes you are right! my fault. Thanks
